# 
# Thinkpad Tablet 10 battery raw I2C read application
# GPLv3
#

# CFLAGS=-O2 -Wall
# CFLAGS+=-DDEBUG

PRG=tpt10-bat
OBJ=tpt10-bat.o
SRC=tpt10-bat.c

all: $(PRG)

$(PRG): $(OBJ)
	$(CC) -o $(PRG) $(OBJ)

clean:
	rm -f $(PRG) $(OBJ)
